services:
  dynamodb:
    image: amazon/dynamodb-local:2.3.0
    container_name: houses-dynamodb
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/data"]
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/data

volumes:
  dynamodb_data:
